export const listItemsItems = [
    {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
]

export const StaffModel = {
    personnel: {
        type:'نوع',
        first_name: 'نام',
        last_name: 'نام خانوادگی',
        military_rank: 'درجه',
        military_part: 'رسته',
        work_code: 'شماره کارگزینی',
        employment_date: 'تاریخ استخدام',
        employment_type: 'نوع استخدام',
        birth_date: 'تاریخ تولد',
        father_name: 'نام پدر',
        national_id_number: 'شماره ملی',
        marriage_status: 'وضعیت تاهل',
        working_status: 'وضعیت خدمتی',
        phone_number: 'تلفن',
        group_unit: 'یگان جمعی',
    },
    duty: {
        type:'نوع',
        first_name: 'نام',
        last_name: 'نام خانوادگی',
        military_rank: 'درجه',
        military_part: 'رسته',
        dispatch_date: 'تاریخ اعزام',
        duty_date: 'مدت خدمت الزامی',
        discharge_date: 'تاریخ ترخیص',
        birth_date: 'تاریخ تولد',
        father_name: 'نام پدر',
        national_id_number: 'شماره ملی',
        marriage_status: 'وضعیت تاهل',
        working_status: 'وضعیت خدمتی',
        phone_number: 'تلفن',
        group_unit: 'یگان جمعی',
    },
}
